### PR TITLE
Collapsible sidebar

### PR DESCRIPTION
**Pull request by NiklasFerling**
Adds a sidebar with nav menu.
Only added to login, but can be copied when passed in review.

Also added an index.js file so all modules with functions and features can be imported there (only needs one script tag i html head)

### CODE REVIEW

**Comment by ftmkrtgz** [comment]
Hei, I get an error like this in the console "Resource “http://127.0.0.1:5500/login/node_modules/bootstrap/dist/css/bootstrap.min.css” was blocked due to mismatching MIME type (“text/html”) (X-Content-Type-Options: nosniff )." 
If you correct this as follows, the error disappears:  <link
      rel="stylesheet"
      href="/node_modules/bootstrap/dist/css/bootstrap.min.css"
    />

**Review by ftmkrtgz — APPROVED** [review]
Everything works as it should. Sidebar with nav menu are successful.

**Comment by MusaabAbdalla** [comment]
"Hey, it looks like there's a conflict involving three files. To resolve it, consider adding the /dist folder to the .gitignore file. This should address conflicts related to files within the dist folder. Those files are typically generated when running npm run watch or npm run build."

**Comment by MusaabAbdalla** [comment]
Hei Niklas,could you please add this code to src/scss/styles.scss? I'm hoping this will resolve the conflict in this file with the main branch.
```css
body, html {
    height: 100%;
    margin: 0;
    padding: 0;
}


header {
    height: 100%;
    // width: 200px;
    float: left;
}

.nav-pills li a:hover {
   background-color: $primary;
}

h1 {
    font-weight: 700;
}

.list-group-item {
    border-left: 0;
    border-right: 0;
}
```

**Pull request merged**
