### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Teitrheim**
Updated readme with information about the app and how to set it up.

### CODE REVIEW

**Review by ftmkrtgz — APPROVED** [review]
Great, everything is fine, it was a nice explanation.

**Comment by CharlotteValset** [comment]
### Project Overview
### Purpose 
The Daily Planning App is designed to enhance personal productivity and motivation by providing users with a structured and interactive platform for daily and weekly planning. It aims to simplify task management, inspire users through motivational quotes, and offer practical tips and insights for personal growth and efficiency.

### Scope 
The project encompasses the development of a web-based application that serves as a comprehensive planning tool. It targets individuals seeking to organize their tasks, set goals, and track their progress in a visually appealing and user-friendly interface.

### Key Functionalities 
**Task Management:** 
Users can create and organize tasks or activities for the day (logged in users also get a weekly view) into bullet points or detailed lists. 

**Motivational Quotes:** 
The app can provide you with daily motivational quotes to inspire users and encourage task productivity and personal growth. 

**Tips and Insights:** Provides users with valuable tips and insights on improving task management, leveraging new technologies, and adopting efficient strategies. 

**Progress Tracking:** Features the ability to export tasklist as a pdf, enabling users to track completed tasks, milestones, and overall progress.  Also as a logged in user the app stores all the daily tasks for you, and you can view your weekly task calendar.

**User Customization:** Allows users to personalize their planning experience with coloured task categories.

<---- I have updated the description of the app to what it actually does, found some places that had a feature that we dont have in our app. Also added headings, bold font and some space to make it easier to read through---->

**Review by CharlotteValset — CHANGES_REQUESTED** [review]
<---- I have updated the description of the app to what it actually does, found some places that had a feature that we dont have in our app. Also added headings, bold font and some space to make it easier to read through---->

### Project Overview
### Purpose 
The Daily Planning App is designed to enhance personal productivity and motivation by providing users with a structured and interactive platform for daily and weekly planning. It aims to simplify task management, inspire users through motivational quotes, and offer practical tips and insights for personal growth and efficiency.

### Scope 
The project encompasses the development of a web-based application that serves as a comprehensive planning tool. It targets individuals seeking to organize their tasks, set goals, and track their progress in a visually appealing and user-friendly interface.

### Key Functionalities 
**Task Management:** 
Users can create and organize tasks or activities for the day (logged in users also get a weekly view) into bullet points or detailed lists. 

**Motivational Quotes:** 
The app can provide you with daily motivational quotes to inspire users and encourage task productivity and personal growth. 

**Tips and Insights:** Provides users with valuable tips and insights on improving task management, leveraging new technologies, and adopting efficient strategies. 

**Progress Tracking:** Features the ability to export tasklist as a pdf, enabling users to track completed tasks, milestones, and overall progress.  Also as a logged in user the app stores all the daily tasks for you, and you can view your weekly task calendar.

**User Customization:** Allows users to personalize their planning experience with coloured task categories.

**Comment by CharlotteValset** [comment]
Did not see the requested changes in readme going into the main?

**Comment by CharlotteValset** [comment]
<---- This is what you need to change it to---->

### Project Overview
### Purpose 
The Daily Planning App is designed to enhance personal productivity and motivation by providing users with a structured and interactive platform for daily and weekly planning. It aims to simplify task management, inspire users through motivational quotes, and offer practical tips and insights for personal growth and efficiency.

### Scope 
The project encompasses the development of a web-based application that serves as a comprehensive planning tool. It targets individuals seeking to organize their tasks, set goals, and track their progress in a visually appealing and user-friendly interface.

### Key Functionalities 
**Task Management:** 
Users can create and organize tasks or activities for the day (logged in users also get a weekly view) into bullet points or detailed lists. 

**Motivational Quotes:** 
The app can provide you with daily motivational quotes to inspire users and encourage task productivity and personal growth. 

**Tips and Insights:** Provides users with valuable tips and insights on improving task management, leveraging new technologies, and adopting efficient strategies. 

**Progress Tracking:** Features the ability to export tasklist as a pdf, enabling users to track completed tasks, milestones, and overall progress.  Also as a logged in user the app stores all the daily tasks for you, and you can view your weekly task calendar.

**User Customization:** Allows users to personalize their planning experience with coloured task categories.

**Comment by CharlotteValset** [comment]
I did not add the changes to the readme file itself, but added a suggestion to how it can be improved in a request change comment

**Pull request merged**
