### PR TITLE
Implemented functions for user login and registration using Noroff API

### PR DESCRIPTION
**Pull request by Ulvounth**
Added login and registration functionality using the Noroff API. This update includes:

- Sending user credentials to the Noroff API for login and storing the access token and user details in local storage for authenticated sessions.

- Allowing new users to register by providing their details to the Noroff API and handling the API's response.

- Basic error handling for both processes to inform users of any login or registration issues.

### CODE REVIEW

**Review by lordaake — CHANGES_REQUESTED** [review]
I see your using v2 API.
Actually the Noroff API V2 has URL and ALT nested inside avatar. V1 avatar is different from V2.

I think your code should be something like the code below. I tested it with jest and it passed the test however who knows if it will work in action. You can check the API documentation here:
https://docs.noroff.dev/docs/v2/auth/register
image

async function registerUser(name, email, password, avatar = {}) {
    try {
        const body = JSON.stringify({
            name,
            email,
            password,
            avatar: {
                url: avatar.url || '',
                alt: avatar.alt || ''
            }
        });

This change clarifies that avatar is optional and that the function can handle cases where these objects are not provided by the caller. It also aligns with the API documentation, which states that avatar is optional. 
        
This modified function now correctly structures the avatar as object, with url and alt properties.

There are restrictions when it comes to what kind of information the register will accept:

[Restrictions](https://docs.noroff.dev/docs/v2/auth/register#restrictions)

There should come up an error if the person registering does any of the mentioned restrictions wrong. Explaining which one went wrong.
Example: “The name value must not contain punctuation symbols apart from underscore (_).”

**Comment by Ulvounth** [comment]
Thank you, lordaake. I'll make those modifications. Regarding the error, I've already planned to include error handling in the login/register listener code to clarify any issues that arise.

**Comment by Ulvounth** [comment]
The recommended code did not perform as expected during my initial manual tests in a separate project. However, after some adjustments and iterations, I managed to get it functioning correctly. Please review the changed I've made.

**Review by lordaake — APPROVED** [review]
I did tests on your code and they seem to work, register and login works. It adds banner by default. It is possible to add bio also if you want, however probably not useful for this project.

PS C:\Users\Tord\Documents\VS Code Projects\QA> node testRegister2.js
Registration Successful: {
  data: {
    name: 'TestUser22',
    email: 'testuser111@stud.noroff.no',
    bio: null,
    avatar: {
      url: 'https://static.wikia.nocookie.net/avatar/images/a/ae/Aang_at_Jasmine_Dragon.png/revision/latest?cb=20130612174003',
      alt: 'Aang at Jasmine Dragon'
    },
    banner: {
      url: 'https://images.unsplash.com/photo-1579547945413-497e1b99dac0?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&h=500&w=1500',
      alt: 'A blurry multi-colored rainbow background'
    }
  },
  meta: {}
}

PS C:\Users\Tord\Documents\VS Code Projects\QA> node loginTest.js
Login Successful: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzEyLCJuYW1lIjoiVGVzdFVzZXIyMjIxMTEiLCJlbWFpbCI6InRlc3R1c2VyMTExMTFAc3R1ZC5ub3JvZmYubm8iLCJiaW8iOm51bGwsImNyZWF0ZWQiOiIyMDI0LTAzLTIxVDExOjIwOjM4Ljk1OFoiLCJ1cGRhdGVkIjoiMjAyNC0wMy0yMVQxMToyMDozOC45NThaIiwiY3JlZGl0cyI6MTAwMCwidmVudWVNYW5hZ2VyIjpmYWxzZSwiYXZhdGFyIjp7ImlkIjoiMTY5MmNlYWYtYzE0Ny00NTc1LTkyZDYtMTZkM2VjZGI2MjEyIiwidXJsIjoiaHR0cHM6Ly9zdGF0aWMud2lraWEubm9jb29raWUubmV0L2F2YXRhci9pbWFnZXMvYS9hZS9BYW5nX2F0X0phc21pbmVfRHJhZ29uLnBuZy9yZXZpc2lvbi9sYXRlc3Q_Y2I9MjAxMzA2MTIxNzQwMDMiLCJhbHQiOiJBYW5nIGF0IEphc21pbmUgRHJhZ29uIiwic29jaWFsUG9zdElkIjpudWxsLCJhdWN0aW9uTGlzdGluZ0lkIjpudWxsLCJob2xpZGF6ZVZlbnVlSWQiOm51bGwsInVzZXJBdmF0YXJJZCI6NzEyLCJ1c2VyQmFubmVySWQiOm51bGwsImJvb2tJZCI6bnVsbCwib2xkR2FtZUlkIjpudWxsLCJvbmxpbmVTaG9wUHJvZHVjdElkIjpudWxsLCJyYWlueURheXNQcm9kdWN0SWQiOm51bGwsImdhbWVIdWJQcm9kdWN0SWQiOm51bGwsInNxdWFyZUV5ZXNQcm9kdWN0SWQiOm51bGx9LCJiYW5uZXIiOnsiaWQiOiI3OTA5OGEyYi0zNmE2LTRiNGEtOGU5Yi1hNDI1ZWYzZjk0MjkiLCJ1cmwiOiJodHRwczovL2ltYWdlcy51bnNwbGFzaC5jb20vcGhvdG8tMTU3OTU0Nzk0NTQxMy00OTdlMWI5OWRhYzA_Y3JvcD1lbnRyb3B5JmNzPXRpbnlzcmdiJmZpdD1jcm9wJmZtPWpwZyZxPTgwJmg9NTAwJnc9MTUwMCIsImFsdCI6IkEgYmx1cnJ5IG11bHRpLWNvbG9yZWQgcmFpbmJvdyBiYWNrZ3JvdW5kIiwic29jaWFsUG9zdElkIjpudWxsLCJhdWN0aW9uTGlzdGluZ0lkIjpudWxsLCJob2xpZGF6ZVZlbnVlSWQiOm51bGwsInVzZXJBdmF0YXJJZCI6bnVsbCwidXNlckJhbm5lcklkIjo3MTIsImJvb2tJZCI6bnVsbCwib2xkR2FtZUlkIjpudWxsLCJvbmxpbmVTaG9wUHJvZHVjdElkIjpudWxsLCJyYWlueURheXNQcm9kdWN0SWQiOm51bGwsImdhbWVIdWJQcm9kdWN0SWQiOm51bGwsInNxdWFyZUV5ZXNQcm9kdWN0SWQiOm51bGx9LCJpYXQiOjE3MTEwMjA1Njl9.ukzMx8NLzHUHuTo-9psbL_pU7MyyGvSgmuU1qiQ0y3c {
  name: 'TestUser222111',
  email: 'testuser11111@stud.noroff.no',
    url: 'https://static.wikia.nocookie.net/avatar/images/a/ae/Aang_at_Jasmine_Dragon.png/revision/latest?cb=20130612174003',
    alt: 'Aang at Jasmine Dragon'
  },
  banner: {
    url: 'https://images.unsplash.com/photo-1579547945413-497e1b99dac0?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&h=500&w=1500',
    alt: 'A blurry multi-colored rainbow background'
  }
}

I wrote the code like this also and it also worked for me (the test succeeded). Its a bit simplified, although its up to you how you want it:

image

async function registerUser(name, email, password, avatar) {
    // Prepare the payload
    const payload = {
        name,
        email,
        password,
        avatar: avatar ? {
            url: avatar.url,
            alt: avatar.alt || '', // Default to an empty string if not provided
        } : undefined, // Do not include avatar in the payload if it's not provided
    };

    try {
        const response = await fetch(`https://v2.api.noroff.dev/auth/register`, {
            method: 'POST',
            body: JSON.stringify(payload),
            headers: {
                'Content-Type': 'application/json',
            },
        });

        if (response.ok) {
            return await response.json();
        } else {
            // If the response is not ok, read the response body as JSON to get more error information
            const error = await response.json();
            // Log the error
            console.error('API Error:', error);
            // Throw an Error object with the detailed error message
            throw new Error(`API Error: ${error.message || response.statusText}`);
        }
    } catch (error) {
        // This catches network errors and errors thrown from the above block
        console.error('Network or other error:', error);
        throw error; // Rethrow the error to be handled by the caller
    }
}

**Pull request merged**
